site_name: Steel Crown Historical Fencing
site_description: Historical European Martial Arts in Charlotte, NC
site_url: https://steelcrownhistoricalfencing.com/
docs_dir: 'Steel Crown Historical Fencing'
site_dir: site
exclude_docs: |
  Fiore for HEMA Fencers/Fiore Di Libre Lesson*

theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - About: About.md
  - Standards:
    - Instructor Standards: 'Standards/Instructor Standards.md'
    - Student Standards: 'Standards/Student Standards.md'
    - Safety Standards: 'Standards/Safety Standards.md'
  - Fiore Curriculum:
    - History:
      - Introduction: 'Fiore for HEMA Fencers/History/Introduction and Historical Context.md'
      - The Segno & Four Virtues: 'Fiore for HEMA Fencers/History/The Segno, the Four Virtues, and the Structure of the System.md'
    - Glossary: 'Fiore for HEMA Fencers/Glossary.md'
    - Guards:
      - Posta di Donna Destra: 'Fiore for HEMA Fencers/Guards/Posta di Donna Destra.md'
      - Posta di Fenestra: 'Fiore for HEMA Fencers/Guards/Posta di Fenestra.md'
      - Dente di Zenghiaro: 'Fiore for HEMA Fencers/Guards/Dente di Zenghiaro.md'
      - Coda Longa: 'Fiore for HEMA Fencers/Guards/Coda Longa.md'
      - Posta Longa: 'Fiore for HEMA Fencers/Guards/Posta Longa.md'
      - Posta Breve: 'Fiore for HEMA Fencers/Guards/Posta Breve.md'
      - Tutta Porta di Ferro: 'Fiore for HEMA Fencers/Guards/Tutta Porta di Ferro.md'
      - Porta di Ferro Mezzana: 'Fiore for HEMA Fencers/Guards/Porta di Ferro Mezzana.md'
      - Porta di Ferro Alta: 'Fiore for HEMA Fencers/Guards/Porta di Ferro Alta.md'
      - Posta Frontale: 'Fiore for HEMA Fencers/Guards/Posta Frontale.md'
      - Posta Corona: 'Fiore for HEMA Fencers/Guards/Posta Corona.md'
      - Bicorno: 'Fiore for HEMA Fencers/Guards/Bicorno.md'
    - Strikes:
      - Fendente Destra: 'Fiore for HEMA Fencers/Strikes/Fendente Destra.md'
      - Fendente Sinestra: 'Fiore for HEMA Fencers/Strikes/Fendente Sinestra.md'
      - Mezzano Destra: 'Fiore for HEMA Fencers/Strikes/Mezzano Destra.md'
      - Mezzano Sinestra: 'Fiore for HEMA Fencers/Strikes/Mezzano Sinestra.md'
      - Sottano Destra: 'Fiore for HEMA Fencers/Strikes/Sottano Destra.md'
      - Sottano Sinestra: 'Fiore for HEMA Fencers/Strikes/Sottano Sinestra.md'
      - Punta: 'Fiore for HEMA Fencers/Strikes/Punta.md'
